solid was harder
mate-academy/jv-jdbc pull request #18
Opened 2021-05-12 21:34 UTC by IhorRome

2021-05-13 08:28 UTC, kupora3 requested changes

2021-05-13 08:28 UTC, kupora3 commented on src/main/java/mate/jdbc/Main.java
> +        manufacturerToUpdate.setId(2L);
Не понятно, что такое 5L 3L 2L, наверное лучше это вынести в константы или вызывать ИД из самой мануфактуры методом getID после отработки create ид у объекта присвоится

2021-05-13 10:57 UTC, kupora3 approved these changes

2021-05-13 12:41 UTC, KseniiaMakarova requested changes
let's create the `init_db.sql` as well

2021-05-13 12:41 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/Main.java
> +        Manufacturer manufacturerGotById = dao.get(uploadedDell.getId()).orElseThrow();
let's print it out?

2021-05-13 12:41 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/Main.java
> +        apple.setId(uploadedHonda.getId());
this is not how we are supposed to do this

we cannot update the object that is not yet in our database
you should change fields of the object that was already saved with create() method
and then call update()

and you should not update id

2021-05-13 12:41 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +                Long id = generatedKeys.getLong(1);
please see checklist

2021-05-13 12:41 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +        manufacturer.setId(resultSet.getObject(1, Long.class));
```suggestion
        manufacturer.setId(resultSet.getObject("id", Long.class));
```

2021-05-13 12:41 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +                "SELECT id, name, country FROM manufacturers WHERE id = ? AND is_deleted = false";
```suggestion
                "SELECT * FROM manufacturers WHERE id = ? AND is_deleted = false";
```

2021-05-13 12:41 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +                "SELECT id, name, country FROM manufacturers WHERE is_deleted = false;";
same here

2021-05-13 12:41 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            Manufacturer manufacturer = null;
do we need this variable here?

2021-05-13 12:41 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            throw new DataProcessingException("Can't get all data from DB", e);
```suggestion
            throw new DataProcessingException("Can't get all manufacturers from DB", e);
```

2021-05-13 12:41 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +        Manufacturer updatedManufacturer = new Manufacturer();
why do you need this variable? you already receive the updated manufacturer in the method

2021-05-13 12:41 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            updatedManufacturer = get(manufacturer.getId()).orElseThrow();
```suggestion
            return manufacturer;
```

2021-05-13 12:41 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/util/ConnectionUtil.java
> +
redundant empty line

2021-05-13 12:41 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/util/ConnectionUtil.java
> +            throw new DataProcessingException("Can't load JDBC driver ", e);
it is better to throw DataProcessingException only in dao
here we can use RuntimeException

2021-05-13 12:41 UTC, KseniiaMakarova commented on src/main/java/mate/jdbc/util/ConnectionUtil.java
> +            throw new DataProcessingException("Can't get connection with DB ", e);
same

2021-05-14 09:03 UTC, KseniiaMakarova requested changes
please also check out some hidden conversations
some of the comments were not fixed

2021-05-14 09:03 UTC, KseniiaMakarova commented on src/main/resources/init_file.sql
> +                                 `id` int NOT NULL AUTO_INCREMENT,
use `bigint` - not `int`

2021-05-14 09:27 UTC, KseniiaMakarova approved these changes

2024-10-14 09:09 UTC, closed without merging