/
mate-academy/jv-jdbc pull request #481
Opened 2023-01-16 18:12 UTC by diana-lomei

2023-01-17 18:11 UTC, nacenik requested changes

2023-01-17 18:11 UTC, nacenik commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            throw new DataProcessingException("Can't insert manufacturer to DB", e);
add more info to exception, as a variant 
```suggestion
            throw new DataProcessingException("Can't insert manufacturer = " + manufacturer +  "to DB", e);
```

2023-01-17 18:11 UTC, nacenik commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            throw new DataProcessingException("Can't get manufacturer info from DB", e);
Make exception more informative. Fix it in all places

2023-01-17 18:11 UTC, nacenik commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            Manufacturer manufacturer = new Manufacturer();
```suggestion
            Manufacturer manufacturer = null;
```

2023-01-17 18:11 UTC, nacenik commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            return Optional.of(manufacturer);
```suggestion
            return Optional.ofNullable(manufacturer);
```

2023-01-17 18:11 UTC, nacenik commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            Manufacturer manufacturer = new Manufacturer();
If you call default constructor - that's mean you have object with null field, but you don't need to return empty object, you need to return null object with optional wrapper

2023-01-17 18:11 UTC, nacenik commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +        List<Manufacturer> allManufacturerInfo = new ArrayList<>();
```suggestion
        List<Manufacturer> manufacturers = new ArrayList<>();
```

2023-01-17 18:11 UTC, nacenik commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            return createManufacturerStatement.executeUpdate() >= PARAMETER_INDEX_NAME;
```suggestion
            return createManufacturerStatement.executeUpdate() > 0;
```

2023-01-17 18:11 UTC, nacenik commented on src/main/resources/init_db.sql
> +
Where is your script?

2023-01-20 12:24 UTC, okuzan requested changes

2023-01-20 12:24 UTC, okuzan commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            createManufacturerStatement.setLong(1,id);
```suggestion
            createManufacturerStatement.setLong(1, id);
```

2023-01-20 12:24 UTC, okuzan commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            return createManufacturerStatement.executeUpdate() >= 0;
```suggestion
            return createManufacturerStatement.executeUpdate() > 0;
```

2023-01-20 12:24 UTC, okuzan commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            throw new DataProcessingException("Can't delete format from DB", e);
delete what? indicate the manufacturer in the message

2023-01-20 12:24 UTC, okuzan commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            updateStatement.setString(1,manufacturer.getName());
use Ctrl Alt L (for windows) to automatically format code

2023-01-20 12:24 UTC, okuzan commented on src/main/java/mate/jdbc/Main.java
> +        manufacturerDao.delete(2L);
magic numbers are confusing to read, add info what is being tested, or make it a NON_EXISTING_ID constant if that's what is supposed to mean

2023-01-20 17:04 UTC, nacenik requested changes

2023-01-20 17:04 UTC, nacenik commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +    private Manufacturer getManufacturer(ResultSet resultSet) {
```suggestion
    private Manufacturer getManufacturer(ResultSet resultSet) throws SQLException {
```

2023-01-20 17:04 UTC, nacenik commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +        try {
delete try-catch in this method
if you get an SQL exception here better to throw it in the method where it was called. There you have a try-catch block to process it and a more informative message.

2023-01-21 18:04 UTC, aleksandr-bevza approved these changes

2025-02-21 11:56 UTC, closed without merging