taxi
mate-academy/jv-jdbc pull request #529
Opened 2023-02-23 03:47 UTC by Oleksandr-Radovets

2023-02-23 11:10 UTC, Rommelua requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2023-02-23 11:10 UTC, Rommelua commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +        try (Statement statement = connect.createStatement()) {
![image](https://user-images.githubusercontent.com/20326858/220889943-1459cc94-810a-4133-aded-575039db217b.png)

2023-02-24 15:02 UTC, andriy-shulepa requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/11480043/221211624-9fb28d18-5a5b-4bea-888c-b11bb8c5508f.png">

2023-02-27 12:42 UTC, aaananas requested changes

2023-02-27 12:42 UTC, aaananas commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +                manufacturerList.add(manufacturer);
extract a manufacturer  to a separate method

2023-02-27 12:42 UTC, aaananas commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +                manufacturer.setCountry(country);
extract a manufacturer in a separate method

2023-02-27 12:42 UTC, aaananas commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +        Manufacturer manufacturer = new Manufacturer();
```suggestion
        Manufacturer manufacturer = null;
```
if the Manufacturer is not found return a Optional.empty() not an extual instance of Manufacturer

2023-02-27 12:42 UTC, aaananas commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +                manufacturer = new Manufacturer();
```suggestion
                Manufacturer manufacturer = new Manufacturer();
```

2023-02-27 12:42 UTC, aaananas commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +        Manufacturer manufacturer;
```suggestion
```

2023-03-02 10:56 UTC, Rommelua requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2023-03-02 10:56 UTC, Rommelua commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            PreparedStatement preparedStatement = connect.prepareStatement(querySelect);
add PreparedStatement  to TWR
![image](https://user-images.githubusercontent.com/20326858/222408669-61bd11b3-8d0a-4fda-acd2-36b76e92cb6d.png)

2023-03-02 10:56 UTC, Rommelua commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +                + "FROM Manufacturer where id_delete = false";
use uppercase for sql key words

2023-03-02 10:56 UTC, Rommelua commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +        return false;
![image](https://user-images.githubusercontent.com/20326858/222409184-f2e6da4d-1e83-46e7-a671-3783637b5552.png)

2023-03-02 15:36 UTC, aaananas approved these changes

2023-03-02 15:36 UTC, aaananas commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            throw new RuntimeException("is not good connection in method get", throwable);
```suggestion
            throw new RuntimeException("Could not get a manufacturer by id = " + id, throwable);
```

2025-02-04 08:20 UTC, closed without merging