jdbc solution
mate-academy/jv-jdbc pull request #53
Opened 2021-05-14 16:18 UTC by Aalderaan

2021-05-14 17:01 UTC, LayRipper requested changes

2021-05-14 17:01 UTC, LayRipper commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +                    .executeQuery();
```suggestion
            ResultSet resultSet = getManufacturer.executeQuery();
```

2021-05-14 17:01 UTC, LayRipper commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            throw new RuntimeException("Can't delete manufacturer from DB", throwables);
specify id of the manufacturer in error message pls

2021-05-14 19:39 UTC, LayRipper approved these changes

2021-05-17 06:53 UTC, RomanDubovskyi approved these changes

2021-05-17 06:53 UTC, RomanDubovskyi commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +        } catch (SQLException throwables) {
```suggestion
        } catch (SQLException e) {
```

2021-05-17 06:53 UTC, RomanDubovskyi commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +        String insertFormatRequest =
```suggestion
        String updateRequest =
```

2021-05-17 06:53 UTC, RomanDubovskyi commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +                    + manufacturer.getId() + " to DB", throwables);
```suggestion
                    + manufacturer + " to DB", throwables);
```
If you didn't insert it, manufacturer has no id

2021-05-17 06:53 UTC, RomanDubovskyi commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +                        .prepareStatement(deleteRequest, Statement.RETURN_GENERATED_KEYS)) {
do we need RETURN_GENERATED_KEYS

2022-09-19 13:27 UTC, closed without merging