solution implemented
mate-academy/jv-jdbc pull request #595
Opened 2023-04-01 10:24 UTC by dreeeamcatcher

2023-04-01 10:46 UTC, andriy-shulepa requested changes

2023-04-01 10:46 UTC, andriy-shulepa commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +                                 .prepareStatement(insertManufacturer, returnGeneratedKeys)) {
```suggestion
        try (Connection connection = ConnectionUtil.getConnection();
                 PreparedStatement createManufacturerStatement =
                         connection
                                 .prepareStatement(insertManufacturer,  Statement.RETURN_GENERATED_KEYS)) {
```

2023-04-01 10:46 UTC, andriy-shulepa commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +
```suggestion
            return getManufacturerStatement.executeUpdate() > 0;
```
it's better to compare with zero

2023-04-01 10:46 UTC, andriy-shulepa commented on src/main/java/mate/jdbc/lib/Dao.java
> +
needless change

2023-04-02 10:19 UTC, Rommelua approved these changes

2023-04-02 10:19 UTC, Rommelua commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +        try {
better add `throws `to the method signature
```suggestion
```

2024-09-26 14:52 UTC, closed without merging