HW-jv-jdbc-2-Of-June
mate-academy/jv-jdbc pull request #631
Opened 2023-06-02 14:00 UTC by ViktoriiaSvidovska

2023-06-02 15:05 UTC, aaananas requested changes

2023-06-02 15:05 UTC, aaananas commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            = "UPDATE manufacturers SET is_deleted  = true where id = ?";
better create a local variable in each method - this would make code easier to read

2023-06-02 15:05 UTC, aaananas commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            return deleteManufacturersStatement.executeUpdate() >= 1;
```suggestion
            return deleteManufacturersStatement.executeUpdate() > 0;
```

2023-06-02 15:08 UTC, okuzan requested changes

2023-06-02 15:08 UTC, okuzan commented on src/main/java/mate/jdbc/service/ParseManufacturerResultSet.java
> +    public Manufacturer parseResultSet(ResultSet resultSet) throws SQLException {
just create a private utility method in dao. that would be enough

2023-06-02 15:08 UTC, okuzan commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +
extra empty line

2023-06-02 15:08 UTC, okuzan commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +            = "UPDATE manufacturers SET is_deleted  = true where id = ?";
```suggestion
            = "UPDATE manufacturers SET is_deleted = TRUE where id = ?";
```

2023-06-03 09:53 UTC, overpathz approved these changes
LGTM. Consider to fix this little mistake.

2023-06-03 09:53 UTC, overpathz commented on src/main/resources/init_db.sql
> +  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
Please, pay attention to common mistakes checklist
- Let’s use TRUE/FALSE instead of 1/0 with is_deleted column in the sql queries.

2023-10-18 14:58 UTC, closed without merging